name: DeepSDF Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true


    # --------------------
    # Windows setup (vcpkg + GLEW + python deps)
    # --------------------
    - name: Install vcpkg and GLEW on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install glew:x64-windows
        Add-Content -Path $env:GITHUB_ENV -Value "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"

    - name: Ensure Windows Python packages and export PY info
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install numpy matplotlib tqdm

        $pyExe = (Get-Command python).Source
        $pySite = & python -c "import sysconfig; print(sysconfig.get_paths()['purelib'])"
        Add-Content -Path $env:GITHUB_ENV -Value "PYTHON_EXECUTABLE=$pyExe"
        Add-Content -Path $env:GITHUB_ENV -Value "PYTHONPATH=$pySite"

    # --------------------
    # Set up CMake
    # --------------------
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    # --------------------
    # Configure CMake
    # --------------------
    - name: Configure CMake
      shell: bash
      run: |
        set -euo pipefail
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
              -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
              ${ZLIB_INCLUDE_DIR:+-DZLIB_INCLUDE_DIR=$ZLIB_INCLUDE_DIR} \
              ${ZLIB_LIBRARY:+-DZLIB_LIBRARY=$ZLIB_LIBRARY} \
              -DCMAKE_VERBOSE_MAKEFILE=ON

    # --------------------
    # Build Pangolin first
    # --------------------
    - name: Build Pangolin (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        cmake --build build --config Release --target pangolin_proj

    
    - name: Build remaining targets (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        cmake --build build --config Release
