name: DeepSDF Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    # --------------------
    # Install vcpkg and GLEW
    # --------------------
    - name: Install vcpkg and GLEW
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install glew:x64-windows

    # --------------------
    # Install Python packages
    # --------------------
    - name: Install Python packages
      shell: pwsh
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install numpy matplotlib tqdm

        $pyExe = (Get-Command python).Source
        $pySite = & python -c "import sysconfig; print(sysconfig.get_paths()['purelib'])"
        echo "PYTHON_EXECUTABLE=$pyExe" >> $env:GITHUB_ENV
        echo "PYTHONPATH=$pySite" >> $env:GITHUB_ENV

    # --------------------
    # Configure CMake
    # --------------------
    - name: Configure CMake
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # Full path to vcpkg toolchain
        $env:CMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"

        # Configure CMake
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release `
              "-DCMAKE_TOOLCHAIN_FILE=$env:CMAKE_TOOLCHAIN_FILE" `
              "-DPYTHON_EXECUTABLE=$env:PYTHON_EXECUTABLE" `
              "-DZLIB_INCLUDE_DIR=${{ github.workspace }}\build\zlib-install\include" `
              "-DZLIB_LIBRARY=${{ github.workspace }}\build\zlib-install\lib\zlibstatic.lib" `
              -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Build Pangolin
      shell: pwsh
      run: |
        # Ensure vcpkg toolchain is set for the ExternalProject
        cmake --build build --config Release --target pangolin_proj -- /m:1
        # Force Pangolin to pick up GLEW from vcpkg
        cmake --build build --config Release --target pangolin_proj -- /p:CMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"

    # --------------------
    # Build remaining DeepSDF targets
    # --------------------
    - name: Build DeepSDF targets
      shell: pwsh
      run: |
        cmake --build build --config Release
