name: DeepSDF Build

on:
  push:
  pull_request:
  workflow_dispatch:  # optional manual run

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    # --------------------
    # Checkout repository
    # --------------------
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    # --------------------
    # macOS dependencies
    # --------------------
    - name: Setup macOS Python and dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install glew zlib
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel numpy matplotlib tqdm

    # --------------------
    # Windows dependencies (vcpkg)
    # --------------------
    - name: Install vcpkg and GLEW on Windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bash
        ./vcpkg install glew:x64-windows
        echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

    # --------------------
    # Set up CMake
    # --------------------
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    # --------------------
    # Configure CMake
    # --------------------
    - name: Configure CMake
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "macOS" ]; then
          source venv/bin/activate
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
                -DPYTHON_EXECUTABLE=$(which python)
        else
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
                ${env:CMAKE_TOOLCHAIN_FILE:+-DCMAKE_TOOLCHAIN_FILE=${env:CMAKE_TOOLCHAIN_FILE}}
        fi

    # --------------------
    # Build
    # --------------------
    - name: Build
      shell: bash
      run: cmake --build build --config Release -- -j 2
